package com.shopperspoint.enums;

public enum OrderStatus {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    DELIVERED,
    CANCELLED,
    ORDER_REJECTED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    RETURN_REQUESTED,
    RETURN_REJECTED,
    RETURN_APPROVED,
    PICK_UP_INITIATED,
    PICK_UP_COMPLETED,
    CLOSED;
}
